Repository artipie/rpm-adapter, pull requests merged in 2020-07, with the labels that each got.

#309 #166 - assertions for metadata in RpmITCase
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/files/TestBundle.java
Labels: role/REV

#308 #307 - NodeHasPkgCount fully implemented
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Labels: role/REV, scope

#296 For #277: add tests to PrimaryOutputTests
  src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
  src/test/resources-binary/repodata/libdeflt-primary.xml.example
Labels: role/REV, scope

#295 For #282: added RpmOptions test
  src/main/java/com/artipie/rpm/RpmOptions.java
  src/test/java/com/artipie/rpm/RpmOptionsTest.java
Labels: role/REV, scope

#313 #299 - Improvements to PackagesCount
  src/main/java/com/artipie/rpm/meta/PackagesCount.java
  src/test/java/com/artipie/rpm/meta/PackagesCountTest.java
Labels: role/REV, scope

#302 #290 - IT case with dnf
  pom.xml
  src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
  src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
  src/test/java/com/artipie/rpm/http/RpmSliceYumITCase.java
Labels: role/DEV, scope

#312 #311 - StorageHasMetadata matcher
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java
  src/test/java/com/artipie/rpm/hm/StorageHasMetadata.java
Labels: role/REV

#322 #315 - introduced Repodata abstraction
  src/main/java/com/artipie/rpm/ModifiableRepository.java
  src/main/java/com/artipie/rpm/NamingPolicy.java
  src/main/java/com/artipie/rpm/Repository.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/meta/XmlRepomd.java
  src/main/java/com/artipie/rpm/pkg/Metadata.java
  src/main/java/com/artipie/rpm/pkg/MetadataFile.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/main/java/com/artipie/rpm/pkg/Repodata.java
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Labels: role/REV

#324 #319 - added path() to TestRpm.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/TestRpm.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
  src/test/java/com/artipie/rpm/pkg/FilePackageTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
  src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
Labels: role/REV

#325 #236 - created PrecedingMetadata with implementation
  src/main/java/com/artipie/rpm/pkg/PrecedingMetadata.java
  src/test/java/com/artipie/rpm/files/GzipTest.java
  src/test/java/com/artipie/rpm/pkg/PrecedingMetadataFromDirTest.java
  src/test/resources-binary/repodata/primary.xml.gz.example
Labels: role/REV

#328 #236 - incremental update for new repo
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Labels: role/REV, scope

#327 #319 - Access test resources via class-loader
  src/test/java/com/artipie/rpm/TestResource.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryChecksumsTest.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java
  src/test/java/com/artipie/rpm/meta/XmlStreamJoinTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
  src/test/java/com/artipie/rpm/pkg/PrecedingMetadataFromDirTest.java
Labels: role/REV

#329 #314 - optimization in ModifiableMetadata
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
  src/test/resources-binary/repodata/other.xml.example
Labels: role/REV

#331 Updated http and asto version
  pom.xml
  src/main/java/com/artipie/rpm/http/RpmSlice.java
  src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
  src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
  src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Labels: 0crat/role/REV, 0crat/scope

#332 #318 - copy rpms with filter by digest
  src/main/java/com/artipie/rpm/misc/RpmByDigestCopy.java
  src/test/java/com/artipie/rpm/misc/RpmByDigestCopyTest.java
Labels: 0crat/role/REV

#334 #333 - use PublisherAs and KeyLastPart from asto
  pom.xml
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/misc/RpmByDigestCopy.java
  src/test/java/com/artipie/rpm/RpmITCase.java
Labels: 0crat/role/REV, 0crat/scope
