Repository artipie/rpm-adapter, pull requests merged in 2020-06, with the labels that each got.

#207 #206 - corrected MetadataFileTest
  pom.xml
  src/main/java/com/artipie/rpm/NamingPolicy.java
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
Labels: role/REV, scope

#209 #203 - add timing extension for tests
  pom.xml
  src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/TimingExtension.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
  src/test/java/com/artipie/rpm/meta/XmlStreamJoin.java
Labels: role/REV, scope

#212 #190 - Throwing InvalidPackageException when package failed to be parsed
  src/main/java/com/artipie/rpm/pkg/FilePackage.java
  src/main/java/com/artipie/rpm/pkg/InvalidPackageException.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
Labels: role/REV, scope

#211 #205 - Add more tests for CliArgumentTests
  src/test/java/com/artipie/rpm/CliArgumentsTest.java
Labels: role/REV, scope

#202 For #117: Added assertions to XmlPrimaryTest
  src/main/java/com/artipie/rpm/meta/XmlPrimary.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
Labels: role/DEV, role/REV, scope

#216 #192 - no blocking operations on incremental update
  pom.xml
  src/main/java/com/artipie/rpm/Rpm.java
Labels: role/REV, scope

#223 #218 - Ignore invalid packages on update
  src/main/java/com/artipie/rpm/Rpm.java
  src/test/java/com/artipie/rpm/RpmTest.java
Labels: role/REV, scope

#231 #191 - Added ChangelogEntry with partial implementation
  src/main/java/com/artipie/rpm/meta/ChangelogEntry.java
  src/test/java/com/artipie/rpm/meta/ChangelogEntryTest.java
Labels: role/REV, scope

#225 #224 - extract repeating code to methods
  src/main/java/com/artipie/rpm/Rpm.java
Labels: role/REV, scope

#239 (#217) - fix cli test
  src/test/java/com/artipie/rpm/CliTest.java
Labels: role/REV, scope

#242 #230 - storage locker
  src/main/java/com/artipie/rpm/misc/StorageLock.java
  src/test/java/com/artipie/rpm/misc/StorageLockerTest.java
  src/test/java/com/artipie/rpm/misc/package-info.java
Labels: role/REV, scope

#237 #191 - Added date parsing to ChangelogEntry
  src/main/java/com/artipie/rpm/meta/ChangelogEntry.java
  src/test/java/com/artipie/rpm/meta/ChangelogEntryTest.java
Labels: role/REV, scope

#247 #235 - test rpm
  src/test/java/com/artipie/rpm/TestRpm.java
Labels: role/REV, scope

#243 #230 - temp dir for metadata
  src/main/java/com/artipie/rpm/ModifiableRepository.java
  src/main/java/com/artipie/rpm/Repository.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/pkg/Metadata.java
  src/main/java/com/artipie/rpm/pkg/MetadataFile.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Labels: role/REV, scope

#199 For #162: RpmUpload Slice
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
  src/test/java/com/artipie/rpm/http/package-info.java
Labels: role/DEV, role/REV, scope

#222 #220 - version to provides
  src/main/java/com/artipie/rpm/meta/XmlPrimary.java
  src/main/java/com/artipie/rpm/pkg/HeaderTags.java
  src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
Labels: role/REV, scope

#252 #226 - class to find file in directory
  src/main/java/com/artipie/rpm/misc/FileInDir.java
  src/test/java/com/artipie/rpm/misc/FileInDirTest.java
Labels: role/REV, scope

#240 (#213) - basic authentication for rpm slice
  pom.xml
  src/main/java/com/artipie/rpm/http/RpmSlice.java
Labels: role/REV, scope

#229 #228 - skip invalid packages on incremental update
  src/main/java/com/artipie/rpm/ModifiableRepository.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/test/java/com/artipie/rpm/RpmTest.java
Labels: role/REV, scope

#256 #253 - RpmUpload implemented
  src/main/java/com/artipie/rpm/http/RpmSlice.java
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Labels: role/REV, scope

#264 #263 - rename rpm method
  src/main/java/com/artipie/rpm/Rpm.java
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/RpmTest.java
Labels: role/REV, scope

#251 (#248) - Use TestRpm in tests
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/RpmTest.java
  src/test/java/com/artipie/rpm/TestRpm.java
Labels: role/REV, scope

#210 For #110: Added meaningful error for broken package in Rpm.batchUpdate
  src/test/java/com/artipie/rpm/RpmTest.java
Labels: role/REV, scope

#258 (#257) - Use FileInDir wherever possible
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/misc/FileInDir.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
  src/test/java/com/artipie/rpm/misc/FileInDirTest.java
Labels: role/REV, scope

#267 #260 - Added override param parsing to RpmUpload.Request
  pom.xml
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
Labels: role/REV, scope

#266 #73 - update readme
  README.md
Labels: role/REV, scope

#261 #259 - RpmSlice integration test
  .github/workflows/integration-test.yml
  pom.xml
  src/main/java/com/artipie/rpm/http/RpmSlice.java
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/TestRpm.java
  src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
  src/test/resources-binary/time-1.7-45.el7.x86_64.rpm
Labels: role/REV, scope

#274 Created matcher to compare xmls
  pom.xml
  src/main/java/com/artipie/rpm/hm/IsXmlEqual.java
  src/main/java/com/artipie/rpm/hm/package-info.java
  src/test/java/com/artipie/rpm/meta/ByPkgidAttrTest.java
  src/test/java/com/artipie/rpm/meta/XmlAlterTest.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinTest.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java
  src/test/java/com/artipie/rpm/meta/XmlStreamJoinTest.java
  src/test/resources-binary/repodata/other.xml.example.second
  src/test/resources-binary/repodata/primary.xml.example.first
Labels: role/REV, scope

#270 #260 - Checking for conflict in RpmUpload
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Labels: role/REV, scope

#272 #241 - added generated metadata files and PrimaryOutput test
  src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
  src/test/resources-binary/repodata/abc-filelists.xml
  src/test/resources-binary/repodata/abc-other.xml
  src/test/resources-binary/repodata/abc-primary.xml
  src/test/resources-binary/repodata/libdeflt-filelists.xml
  src/test/resources-binary/repodata/libdeflt-other.xml
  src/test/resources-binary/repodata/libdeflt-primary.xml
Labels: role/REV, scope

#279 #271 - Added skip_update param reading to RpmUpload.Request
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
Labels: role/REV, scope

#276 #275 - extracted repo settings to enum
  src/main/java/com/artipie/rpm/CliArguments.java
  src/main/java/com/artipie/rpm/RpmOptions.java
Labels: role/REV, scope

#269 #241 - metadata has packages amount
  pom.xml
  src/test/java/com/artipie/rpm/hm/IsXmlEqual.java
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java
  src/test/java/com/artipie/rpm/hm/package-info.java
Labels: role/DEV, scope

#283 #281 - repository configuration abstraction
  src/main/java/com/artipie/rpm/Cli.java
  src/main/java/com/artipie/rpm/CliArguments.java
  src/main/java/com/artipie/rpm/RepoConfig.java
  src/test/java/com/artipie/rpm/CliArgumentsTest.java
Labels: role/REV, scope

#280 #273 - IT case for rpm repo
  src/main/java/com/artipie/rpm/http/RpmSlice.java
  src/test/java/com/artipie/rpm/http/RpmSliceYumITCase.java
Labels: role/REV, scope

#289 #271 - Skip update support in RpmUpload
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Labels: role/REV, scope

#291 #286 - RepoConfig simple implementation and usage in Rpm
  src/main/java/com/artipie/rpm/RepoConfig.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/http/RpmSlice.java
  src/main/java/com/artipie/rpm/http/RpmUpload.java
  src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
  src/test/java/com/artipie/rpm/http/RpmSliceYumITCase.java
  src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Labels: role/REV

#292 #287 - RepoConfig.FromYaml implemented
  pom.xml
  src/main/java/com/artipie/rpm/RepoConfig.java
  src/main/java/com/artipie/rpm/RpmOptions.java
  src/test/java/com/artipie/rpm/RepoConfigFromYamlTest.java
Labels: role/REV, scope

#293 #278 - Extracted FilePackageHeader from FilePackage
  src/main/java/com/artipie/rpm/pkg/FilePackage.java
  src/main/java/com/artipie/rpm/pkg/FilePackageHeader.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
  src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
Labels: role/REV, scope

#297 Try exclude resources
  pom.xml
Labels: role/DEV, scope

#284 (#265) - Add TestRpm.name()
  src/test/java/com/artipie/rpm/TestRpm.java
  src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
Labels: role/REV, scope

#215 #176 - Add a more tests - Cli and CliArguments
  src/test/java/com/artipie/rpm/CliTest.java
Labels: role/REV, scope

#301 Aibolit style checker
  .github/workflows/experimental.yml
Labels: role/REV, scope

#305 #154 - test for FilePackage
  src/main/java/com/artipie/rpm/pkg/FilePackage.java
  src/main/java/com/artipie/rpm/pkg/PackageOutput.java
  src/test/java/com/artipie/rpm/TestRpm.java
  src/test/java/com/artipie/rpm/pkg/FilePackageTest.java
Labels: role/REV

#294 For #285: verify package attribute on NodeHasPkgCount
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java
  src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java
  src/test/resources-binary/repodata/wrong-package.xml.example
Labels: role/REV, scope

#306 #299 - Added PackagesCount class
  src/main/java/com/artipie/rpm/meta/PackagesCount.java
  src/test/java/com/artipie/rpm/meta/PackagesCountTest.java
Labels: role/REV, scope
