Repository artipie/rpm-adapter, pull requests merged in 2020-05, with the labels that each got.

#157 For #85: added test for repomd.xml update
  src/test/java/com/artipie/rpm/RpmITCase.java
Labels: role/REV, scope

#163 For #161 CI fixed
  pom.xml
  src/main/java/com/artipie/rpm/meta/XmlAlter.java
  src/main/java/com/artipie/rpm/meta/XmlRepomd.java
  src/test/java/com/artipie/rpm/meta/XmlFilelistsTest.java
  src/test/java/com/artipie/rpm/meta/XmlOthersTest.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
Labels: role/REV, scope

#160 XmlPrimary uses XmlPackagesFile
  src/main/java/com/artipie/rpm/meta/XmlFile.java
  src/main/java/com/artipie/rpm/meta/XmlOthers.java
  src/main/java/com/artipie/rpm/meta/XmlPackagesFile.java
  src/main/java/com/artipie/rpm/meta/XmlPrimary.java
Labels: role/REV, scope

#170 For #164 get rid of Transformer
  src/main/java/com/artipie/rpm/meta/AlterAttributeEventReader.java
  src/main/java/com/artipie/rpm/meta/XmlAlter.java
  src/test/java/com/artipie/rpm/meta/XmlAlterTest.java
  src/test/java/com/artipie/rpm/meta/XmlPackagesFileTest.java
Labels: role/REV, scope

#172 Extract Cli parsing argument from Cli
  src/main/java/com/artipie/rpm/Cli.java
  src/main/java/com/artipie/rpm/CliArguments.java
  src/test/java/com/artipie/rpm/CliTest.java
Labels: role/REV, scope

#171 For #141 Join xmls
  src/main/java/com/artipie/rpm/ModifiableRepository.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java
  src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/main/java/com/artipie/rpm/pkg/OthersOutput.java
  src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
  src/test/java/com/artipie/rpm/files/TestBundle.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinTest.java
Labels: role/REV, scope

#173 For #130: added changelog generation test for XmlOthers
  src/main/java/com/artipie/rpm/meta/XmlOthers.java
  src/test/java/com/artipie/rpm/meta/XmlOthersTest.java
Labels: role/REV, scope

#184 Cleanup on complete
  src/main/java/com/artipie/rpm/Rpm.java
  src/test/java/com/artipie/rpm/RpmITCase.java
Labels: role/REV, scope

#185 For #129: Optional filelists on the command line
  README.md
  src/main/java/com/artipie/rpm/Cli.java
  src/main/java/com/artipie/rpm/CliArguments.java
Labels: role/REV, scope

#174 For #107: added filelists.xml content assertions
  src/test/java/com/artipie/rpm/meta/XmlFilelistsTest.java
Labels: role/REV, scope

#189 Updated ASTO dependency
  .github/workflows/integration-test.yml
  pom.xml
  src/main/java/com/artipie/rpm/Cli.java
  src/main/java/com/artipie/rpm/FileChecksum.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/test/java/com/artipie/rpm/RpmITCase.java
Labels: role/REV, scope

#158 For #63: Added unit test to Rpm
  src/test/java/com/artipie/rpm/RpmTest.java
Labels: role/REV, scope

#180 For #82: xmlothers changelog refinement
  src/main/java/com/artipie/rpm/meta/XmlOthers.java
  src/main/java/com/artipie/rpm/pkg/HeaderTags.java
  src/main/java/com/artipie/rpm/pkg/OthersOutput.java
  src/test/java/com/artipie/rpm/meta/XmlOthersTest.java
Labels: role/REV, scope

#181 For #178 incremental update
  src/main/java/com/artipie/rpm/ModifiableRepository.java
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/files/Gzip.java
  src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/main/java/com/artipie/rpm/pkg/OthersOutput.java
  src/test/java/com/artipie/rpm/RpmITCase.java
  src/test/java/com/artipie/rpm/files/GzipTest.java
  src/test/resources-binary/abc-1.01-26.git20200127.fc32.ppc64le.rpm
  src/test/resources-binary/libdeflt1_0-2020.03.27-25.1.armv7hl.rpm
  src/test/resources-binary/repodata/primary.xml.example.gz
Labels: role/REV, scope

#187 Add more tests for FilePackage.Headers
  src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
Labels: role/REV, scope

#183 ModifiableMetadata test
  src/main/java/com/artipie/rpm/meta/XmlMaid.java
  src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
  src/test/resources-binary/repodata/primary.xml.example
  src/test/resources-binary/repodata/primary.xml.example.gz
Labels: role/REV, scope

#186 For #159 xml packages file fix
  src/main/java/com/artipie/rpm/meta/XmlFilelists.java
  src/main/java/com/artipie/rpm/meta/XmlOthers.java
  src/main/java/com/artipie/rpm/meta/XmlPackage.java
  src/main/java/com/artipie/rpm/meta/XmlPackagesFile.java
  src/main/java/com/artipie/rpm/meta/XmlPrimary.java
  src/test/java/com/artipie/rpm/meta/XmlPackagesFileTest.java
Labels: role/DEV, scope

#196 Xml join optimization
  src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java
  src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
  src/test/java/com/artipie/rpm/meta/XmlMetaJoinTest.java
  src/test/resources/log4j.properties
Labels: role/REV, scope

#198 For #113: added CliArguments tests
  src/main/java/com/artipie/rpm/CliArguments.java
  src/test/java/com/artipie/rpm/CliArgumentsTest.java
Labels: role/REV, scope

#175 For #106: fixed MetadataFileTest
  pom.xml
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
Labels: role/REV, scope

#197 For #193: XmlPackage usages
  src/main/java/com/artipie/rpm/Rpm.java
  src/main/java/com/artipie/rpm/meta/XmlOthers.java
  src/main/java/com/artipie/rpm/meta/XmlPackage.java
  src/main/java/com/artipie/rpm/meta/XmlPrimary.java
  src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
  src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java
  src/main/java/com/artipie/rpm/pkg/MetadataFile.java
  src/main/java/com/artipie/rpm/pkg/OthersOutput.java
  src/main/java/com/artipie/rpm/pkg/PackageOutput.java
  src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
  src/test/java/com/artipie/rpm/meta/XmlPackagesFileTest.java
  src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
  src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Labels: role/DEV, role/REV, scope
