Repository artipie/rpm-adapter, pull requests merged in 2021-06, with the labels that each got.

#417 Remove from empty indexes
  src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
  src/test/java/com/artipie/rpm/RpmMetadataRemoveTest.java
  src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java
  src/test/resources-binary/repodata/empty/filelists_1.xml.example
  src/test/resources-binary/repodata/empty/filelists_2.xml.example
  src/test/resources-binary/repodata/empty/primary_1.xml.example
  src/test/resources-binary/repodata/empty/primary_2.xml.example
  src/test/resources-binary/repodata/primary.xml.example_maid.first
  src/test/resources-binary/repodata/primary.xml.example_maid.second
Labels: ci/passed, review

#418 Made input stream in RpmMetadata.MetadataItem optional
  src/main/java/com/artipie/rpm/RpmMetadata.java
  src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java
  src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java
  src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java
  src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Labels: ci/passed, review

#419 Added test with absent input streams for `RpmMetadata.Append`
  src/test/java/com/artipie/rpm/RpmMetadataAppendTest.java
Labels: ci/passed, merge

#422 bench: using benchmark storage, extracted project
  README.md
  benchmarks/README.md
  benchmarks/pom.xml
  benchmarks/src/main/java/com/artipie/rpm/benchmarks/RpmBench.java
  benchmarks/src/main/java/com/artipie/rpm/benchmarks/RpmMetadataAppendBench.java
  benchmarks/src/main/java/com/artipie/rpm/benchmarks/RpmMetadataRemoveBench.java
  benchmarks/src/main/java/com/artipie/rpm/benchmarks/package-info.java
  pom.xml
Labels: benchmarks
